<%@ page language="java" import="java.util.*" pageEncoding="utf-8"%>
<%@page import="com.kesd.common.*"%>
<%@page import="com.kesd.comntpara.ComntUseropDef"%>
<%
	String path = request.getContextPath();
	String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";
    
    out.println("<script>");
    out.println("var SDDef={");
    out.println("SUCCESS : '" 	+ SDDef.SUCCESS + "',"); 
    out.println("FAIL : '" 		+ SDDef.FAIL + "',");
    
    out.println("TRUE : '" 	+ SDDef.TRUE + "',"); 
    out.println("FALSE : '" + SDDef.FALSE + "',");    
    
   	out.println("EMPTY : '" 			+ SDDef.EMPTY + "',");
   	out.println("GLOBAL_KE2 : '" 		+ SDDef.GLOBAL_KE2 + "',");
   	out.println("SPLITCOMA: '" 			+ SDDef.SPLITCOMA +"',");
   	out.println("JMRTUID: " 			+ SDDef.JMRTUID +",");
   	out.println("ZBRTUID: " 			+ SDDef.ZBRTUID +",");
   	out.println("GBRTUID: " 			+ SDDef.GBRTUID +",");
   	out.println("BDZRTUID: " 			+ SDDef.BDZRTUID +",");
   	out.println("APPTYPE_BDZ : " 		+ SDDef.APPTYPE_BDZ + ",");
	out.println("APPTYPE_ZB : " 		+ SDDef.APPTYPE_ZB + ",");
	out.println("APPTYPE_GB : " 		+ SDDef.APPTYPE_GB + ",");
	out.println("APPTYPE_JC: " 			+ SDDef.APPTYPE_JC + ",");
	out.println("APPTYPE_NP: " 			+ SDDef.APPTYPE_NP + ",");
	out.println("DATA_BEILV_ONE: " 		+ SDDef.DATA_BEILV_ONE + ",");
	out.println("DATA_BEILV_TWO: " 		+ SDDef.DATA_BEILV_TWO + ",");
	out.println("DATA_BDDL_SINGLE: " 	+ SDDef.DATA_BDDL_SINGLE + ",");
	out.println("DATA_BDDL_MULT: " 		+ SDDef.DATA_BDDL_MULT + ",");
	out.println("DATA_BDDL_ZHENG: " 	+ SDDef.DATA_BDDL_ZHENG + ",");
	out.println("DATA_BDDL_FAN: " 		+ SDDef.DATA_BDDL_FAN + ",");	
	out.println("DATA_SSL_V: " 			+ SDDef.DATA_SSL_V + ",");
	out.println("DATA_SSL_I: " 			+ SDDef.DATA_SSL_I + ",");
	out.println("DATA_SSL_PQ: " 		+ SDDef.DATA_SSL_PQ + ",");
	out.println("DATA_SSL_CS: " 		+ SDDef.DATA_SSL_CS + ",");
	out.println("DATA_HG_TM: " 			+ SDDef.DATA_HG_TM + ",");
	out.println("DATA_HG_LIMIT: " 		+ SDDef.DATA_HG_LIMIT + ",");
	out.println("DATA_HG_PJ: " 			+ SDDef.DATA_HG_PJ + ",");
	out.println("DATA_I_TM: " 			+ SDDef.DATA_I_TM + ",");
	out.println("DATA_I_LIMIT: " 		+ SDDef.DATA_I_LIMIT + ",");
	out.println("DATA_P_ZERO: " 		+ SDDef.DATA_P_ZERO + ",");
	out.println("DATA_P_LIMIT: " 		+ SDDef.DATA_P_LIMIT + ",");
	out.println("DATA_DX_TIMES: " 		+ SDDef.DATA_DX_TIMES + ",");
	out.println("DATA_DX_TM: " 			+ SDDef.DATA_DX_TM + ",");
	out.println("DATA_DX_LAST: " 		+ SDDef.DATA_DX_LAST + ",");
	out.println("DATA_MAX_ROW: " 		+ SDDef.DATA_MAX_ROW + ",");
	out.println("DEFAULT_VALUE1OR2: 0,");//一次侧二次侧值
   	out.println("BASEPATH : '" + basePath + "'");   	
   	out.println("};");    
   	
   	out.println("var Dict={");
   	out.println("DICTITEM_DATATYPE : '" 		+ Dict.DICTITEM_DATATYPE + "',");
   	out.println("DICTITEM_FEETYPE : '" 			+ Dict.DICTITEM_FEETYPE + "',");
   	out.println("DICTITEM_CSSTAND : '" 			+ Dict.DICTITEM_CSSTAND + "',");
   	out.println("DICTITEM_METERTYPE : '" 		+ Dict.DICTITEM_METERTYPE + "',");
  	out.println("DICTITEM_FACTORY : '" 			+ Dict.DICTITEM_FACTORY + "',");
   	out.println("DICTITEM_TASKTYPE : '" 		+ Dict.DICTITEM_TASKTYPE + "',");
   	out.println("DICTITEM_CHANTYPE : '" 		+ Dict.DICTITEM_CHANTYPE + "',");
   	out.println("DICTITEM_RASCHECKTYPE : '" 	+ Dict.DICTITEM_RASCHECKTYPE + "',");
   	out.println("DICTITEM_MONITORFLAG : '" 		+ Dict.DICTITEM_MONITORFLAG + "',");
   	out.println("DICTITEM_PERIODUINT : '" 		+ Dict.DICTITEM_PERIODUINT + "',");
   	out.println("DICTITEM_FLNUMBER : '" 		+ Dict.DICTITEM_FLNUMBER + "',");
   	out.println("DICTITEM_METERPROT : '" 		+ Dict.DICTITEM_METERPROT + "',");
   	out.println("DICTITEM_VOLTGRADE : '" 		+ Dict.DICTITEM_VOLTGRADE + "',");
   	out.println("DICTITEM_POWERTYPE : '" 		+ Dict.DICTITEM_POWERTYPE + "',");
   	out.println("DICTITEM_TRMODEL : '" 			+ Dict.DICTITEM_TRMODEL + "',");
   	out.println("DICTITEM_RTUPROTTYPE : '" 		+ Dict.DICTITEM_RTUPROTTYPE + "',");
   	out.println("DICTITEM_BDZRTUPROTTYPE : '" 	+ Dict.DICTITEM_BDZRTUPROTTYPE + "',");
   	out.println("DICTITEM_ZGRTUPROTTYPE : '" 	+ Dict.DICTITEM_ZGRTUPROTTYPE + "',");
   	out.println("DICTITEM_JMRTUPROTTYPE : '" 	+ Dict.DICTITEM_JMRTUPROTTYPE + "',");
   	out.println("DICTITEM_ADDRJZ : '" 			+ Dict.DICTITEM_ADDRJZ + "',");
   	out.println("DICTITEM_RTUFACTORY : '" 		+ Dict.DICTITEM_RTUFACTORY + "',");
   	out.println("DICTITEM_INTNUMBER : '" 		+ Dict.DICTITEM_INTNUMBER + "',");
   	out.println("DICTITEM_DECNUMBER : '" 		+ Dict.DICTITEM_DECNUMBER + "',");
   	out.println("DICTITEM_CHANPORT : '" 		+ Dict.DICTITEM_CHANPORT + "',");
   	out.println("DICTITEM_CHECKTYPE : '" 		+ Dict.DICTITEM_CHECKTYPE + "',");
   	out.println("DICTITEM_BAUDTYPE : '" 		+ Dict.DICTITEM_BAUDTYPE + "',");
   	out.println("DICTITEM_DATABITTYPE : '" 		+ Dict.DICTITEM_DATABITTYPE + "',");
   	out.println("DICTITEM_STOPTYPE : '" 		+ Dict.DICTITEM_STOPTYPE + "',");
   	out.println("DICTITEM_USEFLAG : '" 			+ Dict.DICTITEM_USEFLAG + "',");
   	out.println("DICTITEM_JXFS : '" 			+ Dict.DICTITEM_JXFS + "',");
   	out.println("DICTITEM_METERFACTORY : '" 	+ Dict.DICTITEM_METERFACTORY + "',");
   	out.println("DICTITEM_LINETYPE : '" 		+ Dict.DICTITEM_LINETYPE + "',");
   	out.println("DICTITEM_YESFLAG : '" 			+ Dict.DICTITEM_YESFLAG + "',");
   	out.println("DICTITEM_LINEATTR : '" 		+ Dict.DICTITEM_LINEATTR + "',");
   	out.println("DICTITEM_TASKDATATYPE : '" 	+ Dict.DICTITEM_TASKDATATYPE + "',");
   	out.println("DICTITEM_TJJCJG : '" 			+ Dict.DICTITEM_TJJCJG + "',");
   	
   
   out.println("DICTITEM_ZDLMP : '" 			+ Dict.DICTITEM_ZDLMP + "',");
   out.println("DICTITEM_FLDLMP : '" 			+ Dict.DICTITEM_FLDLMP + "',");
   out.println("DICTITEM_SSLMP : '" 			+ Dict.DICTITEM_SSLMP + "',");
   out.println("DICTITEM_XLMP : '" 				+ Dict.DICTITEM_XLMP + "',");
   out.println("DICTITEM_DLMINDL : '" 			+ Dict.DICTITEM_DLMINDL + "',");
   out.println("DICTITEM_DLMINQX : '" 			+ Dict.DICTITEM_DLMINQX + "',");
   out.println("DICTITEM_DLDATATC : '" 			+ Dict.DICTITEM_DLDATATC + "',");
   out.println("DICTITEM_DL719BUF : '" 			+ Dict.DICTITEM_DL719BUF + "',");
   out.println("DICTITEM_BUFFER : '" 			+ Dict.DICTITEM_BUFFER + "',");
   out.println("DICTITEM_ACCOUNTUNIT : '" 		+ Dict.DICTITEM_ACCOUNTUNIT + "',");
   out.println("DICTITEM_ACCOUNTENDTIME : '" 	+ Dict.DICTITEM_ACCOUNTENDTIME + "',");
   out.println("DICTITEM_STATOBJTYPE : '" 		+ Dict.DICTITEM_STATOBJTYPE + "',");
   out.println("DICTITEM_SWITCHTYPE : '" 		+ Dict.DICTITEM_SWITCHTYPE + "',");
   out.println("DICTITEM_SWITCHSTATUS : '" 		+ Dict.DICTITEM_SWITCHSTATUS + "',");
   out.println("DICTITEM_CTRLLOGIC : '" 		+ Dict.DICTITEM_CTRLLOGIC + "',");
   out.println("DICTITEM_INPUTFLAG : '" 		+ Dict.DICTITEM_INPUTFLAG + "',");
   
   	out.println("DICTITEM_MPTYPE : '" 			+ Dict.DICTITEM_MPTYPE + "',");
   	out.println("DICTITEM_RESIDENTUSERTYPE : '" + Dict.DICTITEM_RESIDENTUSERTYPE + "',");
   	out.println("DICTITEM_FREEZEUINT : '" 		+ Dict.DICTITEM_FREEZEUINT + "',");
   	out.println("DICTITEM_PROTOBJECTTYPE : '" 	+ Dict.DICTITEM_PROTOBJECTTYPE + "',");
   	out.println("DICTITEM_INSTSITE : '" 		+ Dict.DICTITEM_INSTSITE + "',");
   	out.println("DICTITEM_REPORTTYPE : '" 		+ Dict.DICTITEM_REPORTTYPE + "',"); 
  	out.println("DICTITEM_STARTUPFLAG : '" 		+ Dict.DICTITEM_STARTUPFLAG + "',");
  	out.println("DICTITEM_TIMES : '" 			+ Dict.DICTITEM_TIMES + "',");
   	out.println("DICTITEM_CONTROL_TYPE : '" 	+ Dict.DICTITEM_CONTROL_TYPE + "',");
   	out.println("DICTITEM_TASKOBJECTAREA : '" 	+ Dict.DICTITEM_TASKOBJECTAREA + "',");
   	out.println("DICTITEM_TASKOBJECTTYPE : '" 	+ Dict.DICTITEM_TASKOBJECTTYPE + "',");
   	out.println("DICTITEM_TASKEXECTYPE : '" 	+ Dict.DICTITEM_TASKEXECTYPE + "',");
   	out.println("DICTITEM_TASKEXECCYCLETYPE : '" + Dict.DICTITEM_TASKEXECCYCLETYPE + "',");
  	out.println("DICTITEM_MAINMETFLAG : '" 		+ Dict.DICTITEM_MAINMETFLAG + "',");
  	out.println("DICTITEM_WIRINGMODE : '" 		+ Dict.DICTITEM_WIRINGMODE + "',");
  	out.println("DICTITEM_TASKRECALL : '" 		+ Dict.DICTITEM_TASKRECALL + "',");
  	out.println("DICTITEM_FUKONGMANTYPE : '" 	+ Dict.DICTITEM_FUKONGMANTYPE + "',");
  	out.println("DICTITEM_FUKONGRIGHT : '" 		+ Dict.DICTITEM_FUKONGRIGHT + "',");
  	out.println("DICTITEM_DOCRIGHT : '" 		+ Dict.DICTITEM_DOCRIGHT + "',");
  	out.println("DICTITEM_CHGMETEBEILV : '" 	+ Dict.DICTITEM_CHGMETEBEILV + "',");
  	out.println("DICTITEM_ADDDIRECTION : '" 	+ Dict.DICTITEM_ADDDIRECTION + "',");
  	out.println("DICTITEM_ADDFLAG : '" 			+ Dict.DICTITEM_ADDFLAG + "',");	
  	out.println("DICTITEM_XSPHTYPE : '" 		+ Dict.DICTITEM_XSPHTYPE + "',");	
  	out.println("DICTITEM_WGFLAG : '" 			+ Dict.DICTITEM_WGFLAG + "',");	
  	out.println("DICTITEM_XSPHITEMTYPE : '" 	+ Dict.DICTITEM_XSPHITEMTYPE + "',");	
   	out.println("DICTITEM_RTUATTRTYPE : '" 		+ Dict.DICTITEM_RTUATTRTYPE + "',");
   	out.println("DICTITEM_ENDTIMETYPE : '" 		+ Dict.DICTITEM_ENDTIMETYPE + "',");
   	out.println("DICTITEM_PROTDATATYPE : '" 	+ Dict.DICTITEM_PROTDATATYPE + "',");
   	out.println("DICTITEM_PREPAYTYPE : '" 		+ Dict.DICTITEM_PREPAYTYPE + "',");
   	out.println("DICTITEM_RTUPOLLID : '" 		+ Dict.DICTITEM_RTUPOLLID + "',");
   	out.println("DICTITEM_REDIALINNER : '" 		+ Dict.DICTITEM_REDIALINNER + "',"); 
   	out.println("DICTITEM_RTUUPCOMMTYPE : '" 	+ Dict.DICTITEM_RTUUPCOMMTYPE + "',");
   	out.println("DICTITEM_ALARMDELAYTIME : '" 	+ Dict.DICTITEM_ALARMDELAYTIME + "',");
   	out.println("DICTITEM_LIMITPOWERTIME : '" 	+ Dict.DICTITEM_LIMITPOWERTIME + "',");
   	out.println("DICTITEM_HOLDPOWERTIME : '" 	+ Dict.DICTITEM_HOLDPOWERTIME + "',");
   	out.println("DICTITEM_NOCOMMTIME : '" 		+ Dict.DICTITEM_NOCOMMTIME + "',");
   	out.println("DICTITEM_GPRSREDIALINNER : '" 	+ Dict.DICTITEM_GPRSREDIALINNER + "',");
   	out.println("DICTITEM_BDZMPTYPE : '" 		+ Dict.DICTITEM_BDZMPTYPE + "',");
   	out.println("DICTITEM_WGTYPE : '" 			+ Dict.DICTITEM_WGTYPE + "',");
   	out.println("DICTITEM_PAYTYPE : '" 			+ Dict.DICTITEM_PAYTYPE + "',");
   	out.println("DICTITEM_ALARMTYPE : '" 			+ Dict.DICTITEM_ALARMTYPE + "',");
   	out.println("DICTITEM_MAINMPFLAG : '" 			+ Dict.DICTITEM_MAINMPFLAG + "',");
   	
   	out.println("DICTITEM_SIMCARDTYPE : '" 	+ Dict.DICTITEM_SIMCARDTYPE + "',");
   	out.println("DICTITEM_RUNSTATUS : '" 	+ Dict.DICTITEM_RUNSTATUS + "',");
   	out.println("DICTITEM_SUPPORTTYPE : '" 	+ Dict.DICTITEM_SUPPORTTYPE + "',");
   	out.println("DICTITEM_ENCRYPTCOMM : '"	+ Dict.DICTITEM_ENCRYPTCOMM + "',");
   	out.println("DICTITEM_TASKREPORT : '" 	+ Dict.DICTITEM_TASKREPORT + "',");
   	out.println("DICTITEM_CHGMETE : '" 		+ Dict.DICTITEM_CHGMETE + "',");
    out.println("DICTITEM_CHANPORT376 : '" 	+ Dict.DICTITEM_CHANPORT376 + "',");
    out.println("DICTITEM_PROTECTTYPE : '" 	+ Dict.DICTITEM_PROTECTTYPE + "',");
    out.println("DICTITEM_YFFRANK : '" 		+ Dict.DICTITEM_YFFRANK + "',");
    out.println("DICTITEM_RELAYTYPE : '" 	+ Dict.DICTITEM_RELAYTYPE + "',");
    out.println("DICTITEM_CBINTERVALS : '" 	+ Dict.DICTITEM_CBINTERVALS + "',");
    out.println("DICTITEM_CBTIMES : '" 		+ Dict.DICTITEM_CBTIMES + "',");
    out.println("DICTITEM_NETONLINE : '" 	+ Dict.DICTITEM_NETONLINE + "',");
    out.println("DICTITEM_RTUCHANTYPE : '" 	+ Dict.DICTITEM_RTUCHANTYPE + "',");
    out.println("DICTITEM_POWERADDFLAG : '" + Dict.DICTITEM_POWERADDFLAG + "',");
    out.println("DICTITEM_METERCOE : '" 	+ Dict.DICTITEM_METERCOE + "',");
    out.println("DICTITEM_KE485WORKTYPE : '" 	+ Dict.DICTITEM_KE485WORKTYPE + "',");
    out.println("DICTITEM_KEBDZPRROTOCOL : '" 	+ Dict.DICTITEM_KEBDZPRROTOCOL + "',");
    out.println("DICTITEM_METERTYPE_XC : '" 	+ Dict.DICTITEM_METERTYPE_XC + "',");
    out.println("DICTITEM_METERTYPE_KEDYH : '" 	+ Dict.DICTITEM_METERTYPE_KEDYH + "',");
    out.println("DICTITEM_CBINTERVALS_GB : '" 	+ Dict.DICTITEM_CBINTERVALS_GB + "',");
   	out.println("DICTITEM_SAFEINTER : '" 	+ Dict.DICTITEM_SAFEINTER + "',");
   	out.println("DICTITEM_YFFAPPTYPE : '" 	+ Dict.DICTITEM_YFFAPPTYPE + "',");
   	out.println("DICTITEM_YFF_RATEJ_TYPE : '" 	+ Dict.DICTITEM_YFF_RATEJ_TYPE + "',");
   	out.println("DICTITEM_METER_FEE_TYPE : '" 	+ Dict.DICTITEM_METER_FEE_TYPE + "',");
   	out.println("DICTITEM_FEELVTYPE : '" 	+ Dict.DICTITEM_FEELVTYPE + "'"); 
   	out.println("};");
   	
   	out.println("var YDTable={};");
   	out.println("YDTable.TABLECLASS_ORGPARA='"+YDTable.TABLECLASS_ORGPARA+"'");
   	out.println("YDTable.TABLECLASS_LINEFZMAN='"+YDTable.TABLECLASS_LINEFZMAN+"'");
   	out.println("YDTable.TABLECLASS_CONSPARA='"+YDTable.TABLECLASS_CONSPARA+"'");
   	out.println("YDTable.TABLECLASS_RTUPARA='"+YDTable.TABLECLASS_RTUPARA+"'");
    
    out.println("var ComntUseropDef={};");
   	out.println("ComntUseropDef.YFF_DYOPER_GPARASTATE='"+ComntUseropDef.YFF_DYOPER_GPARASTATE+"'");
   	out.println("ComntUseropDef.YFF_GYOPER_GPARASTATE='"+ComntUseropDef.YFF_GYOPER_GPARASTATE+"'");
    out.println("</script>");
    
%>